service: raceflow-update

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  stage: prod
  region: eu-west-2

functions:
  update:
    handler: raceflow.lamba_wrapper

plugins:
  - serverless-python-requirements
