version: 2.1

orbs:
   aws-cli: circleci/aws-cli@1.0
   serverless: circleci/serverless-framework@1.0

workflows:
  sample:
    jobs:
      - build-and-test

jobs:
  build-and-test:
     executor: serverless/default
     steps:
       - checkout
       - aws-cli/setup
       - serverless/setup
       - run: sls deploy
